# fly.toml app configuration file generated for good-old-iris-model-lively-sound-1453 on 2025-01-01T21:38:01+05:30
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'good-old-iris-model-lively-sound-1453'
primary_region = 'bom'
kill_signal = 'SIGINT'
kill_timeout = '5s'

[http_service]
internal_port = 8000
force_https = true
auto_stop_machines = 'stop'
auto_start_machines = true
min_machines_running = 0

[http_service.concurrency]
type = 'connections'
hard_limit = 500
soft_limit = 250

[[vm]]
size = 'performance-1x'
