app = 'good-old-iris-model'
primary_region = 'bom'

[build]

[http_service]
internal_port = 8000
force_https = true
auto_stop_machines = 'stop'
auto_start_machines = true
min_machines_running = 0

# Add health check
[http_service.concurrency]
type = "connections"
hard_limit = 1000
soft_limit = 500

[[vm]]
memory = '2gb'
cpu_kind = 'performance'
cpus = 1

# Add health check endpoint
[metrics]
port = 8000
path = "/hello"
