# fly.toml app configuration file generated for good-old-iris-model on 2025-01-01T21:51:57+05:30
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'good-old-iris-model'
primary_region = 'bom'

[build]

[http_service]
internal_port = 8000
force_https = true
auto_stop_machines = 'stop'
auto_start_machines = true
min_machines_running = 0


[[vm]]
size = 'performance-1x'
