# fly.toml app configuration file for good-old-iris-model
app = "good-old-iris-model"
# "ord" for gpus
primary_region = "bom"
kill_signal = "SIGINT"
kill_timeout = "5s"

[env]
PORT = "8000"

# VM configuration
[[vm]]
# size = "a100-40gb" or "l40s" or "a100-80gb" for gpus

size = "shared-cpu-2x"
memory = "2gb"
cpu_kind = "performance"
cpus = 1

[http_service]
internal_port = 8000
force_https = true
auto_stop_machines = "stop"
auto_start_machines = true
min_machines_running = 0

[http_service.concurrency]
type = "connections"
hard_limit = 500
soft_limit = 250

[[http_service.checks]]
grace_period = "10s"
interval = "30s"
method = "GET"
path = "/"
protocol = "http"
timeout = "5s"

[[services]]
protocol = "tcp"
internal_port = 8000
auto_stop_machines = "stop"
auto_start_machines = true

[[services.ports]]
port = 443
handlers = ["tls"]
[services.ports.tls_options]
alpn = ["h2"]

[services.concurrency]
hard_limit = 500
soft_limit = 250
