# fly.toml app configuration file generated for good-old-iris-model on 2025-01-01T21:51:57+05:30
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'good-old-iris-model'
primary_region = 'bom'

[build]

[http_service]
internal_port = 8000
force_https = true
auto_stop_machines = 'stop'
auto_start_machines = true
min_machines_running = 0


[[vm]]
memory = '2gb'
cpu_kind = 'performance'
cpus = 1

[[services]]
protocol = 'tcp'
internal_port = 8000
auto_stop_machines = true
auto_start_machines = true

[[services.ports]]
port = 443
handlers = ['tls']

[services.ports.tls_options]
alpn = ['h2']

[services.concurrency]
hard_limit = 500
soft_limit = 250
