# fly.toml app configuration file generated for gpu-good-old-iris-model on 2025-01-02T03:08:12+05:30
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'gpu-good-old-iris-model'
primary_region = 'ord'

[build]
dockerfile = './Dockerfile.gpu'

[http_service]
internal_port = 8000
force_https = true
auto_stop_machines = 'stop'
auto_start_machines = true
min_machines_running = 0

[http_service.concurrency]
type = 'connections'
hard_limit = 1000
soft_limit = 500

[[vm]]
size = "l40s"

[[metrics]]
port = 8000
path = '/hello'
https = false
