# See https://fly.io/docs/app-guides/continuous-deployment-with-github-actions/

name: Fly Deploy CPU
on:
  push:
    branches:
      - main
  workflow_dispatch: {}

jobs:
  deploy:
    name: Deploy CPU app
    runs-on: ubuntu-latest
    concurrency: deploy-group-cpu
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - uses: superfly/flyctl-actions/setup-flyctl@master

      # Set Fly secrets
      # check if the secrets are set
      # echo "HF_TOKEN: $# {{ secrets.HF_TOKEN }}"
      # echo "HUGGINGFACE_MODEL_REPO: $# {{ secrets.HUGGINGFACE_MODEL_REPO }}"
      - name: Set Fly secrets
        run: |
          flyctl secrets set --stage --app "good-old-iris-model" "HF_TOKEN=${{ secrets.HF_TOKEN }}"
          flyctl secrets set --stage --app "good-old-iris-model" "HUGGINGFACE_MODEL_REPO=${{ secrets.HUGGINGFACE_MODEL_REPO }}"
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_IO_DEPLOY_TOKEN }}

      - name: check fly secrets
        run: |
          flyctl secrets list --app good-old-iris-model
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_IO_DEPLOY_TOKEN }}

      # Check fly status
      - name: Check fly status
        run: |
          flyctl status --app good-old-iris-model
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_IO_DEPLOY_TOKEN }}

      # Deploy to Fly
      - name: Deploy a docker container to fly.io
        run: flyctl deploy --remote-only --config cpu.fly.toml --dockerfile ./Dockerfile.cpu
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_IO_DEPLOY_TOKEN }}