# See https://fly.io/docs/app-guides/continuous-deployment-with-github-actions/

name: Fly Deploy
on:
  push:
    branches:
      - main
jobs:
  deploy:
    name: Deploy app
    runs-on: ubuntu-latest
    concurrency: deploy-group    # optional: ensure only one action runs at a time
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - uses: superfly/flyctl-actions/setup-flyctl@master

      # Set Fly secrets
      - name: Set Fly secrets
        run: |
          flyctl secrets set --stage --app "good-old-iris-model" "HF_TOKEN=${HF_TOKEN}"
          flyctl secrets set --stage --app "good-old-iris-model" "HUGGINGFACE_MODEL_REPO=${HUGGINGFACE_MODEL_REPO}"
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_IO_DEPLOY_TOKEN }}

      # Check fly status
      - name: Check fly status
        run: |
          flyctl status --app good-old-iris-model
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_IO_DEPLOY_TOKEN }}

      # Deploy to Fly
      - name: Deploy to Fly on push to main
        run: flyctl deploy --remote-only --config fly.toml
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_IO_DEPLOY_TOKEN }}
